backend:
  name: git-gateway
  branch: master

media_folder: "assets/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "inmueble"
    label: "Inmueble"
    folder: "_inmuebles"
    create: true
    slug: "{{year}}--{{month}}--{{day}}--{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Descripción", name: "body", widget: "markdown"}
      - label: "Dirección"
        name: "address"
        widget: "object"
        fields:
          - {label: "Street Address", name: "street", widget: "string", required: false}
          - {label: "Ciudad", name: "city", widget: "string"}
          - {label: "Código Postal", name: "post-code", widget: "string", required: false}
      - {label: "Precio", name: "price", widget: number, type: "int", required: false}
      - {label: "Precio anterior", name: "previous-price", widget: number, type: "int", required: false}
      - label: "Galería"
        name: "gallery"
        widget: "list"
        fields:
          - {label: "Imagen", name: "image", widget: image}
