backend:
  name: git-gateway
  branch: master

media_folder: "assets/images/uploads/originales"

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "inmueble"
    label: "Inmueble"
    folder: "_inmuebles"
    create: true
    slug: "{{year}}--{{month}}--{{day}}--{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Estado", name: "status", widget: "select", options: ["Venta", "Alquiler"]}
      - {label: "Descripción", name: "body", widget: "markdown"}
      - label: "Dirección"
        name: "address"
        widget: "object"
        fields:
          - {label: "Street Address", name: "street", widget: "string", required: false}
          - {label: "Ciudad", name: "city", widget: "string"}
          - {label: "Código Postal", name: "post-code", widget: "string", required: false}
          - {label: "Provincia", name: "region", widget: "string"}
      - {label: "Precio", name: "price", widget: number, type: "int", required: false}
      - {label: "Precio anterior", name: "previous-price", widget: number, type: "int", required: false}
      - label: "Galería"
        name: "gallery"
        widget: "list"
        fields:
          - {label: "Imagen", name: "image", widget: "image"}
      - label: "Datos básicos"
        name: "basic-data"
        widget: "object"
        required: false
        fields:
          - {label: "Superficie construida", name: "superficie-construida", widget: "string", type: "int", min: 0}
          - {label: "Superficia útil", name: "superficie-útil", widget: "number", type: "int", min: 0}
          - {label: "habitaciones", name: "rooms", widget: "number", type: "int", min: 0}
          - {label: "Baños", name: "baths", widget: number, type: "int", min: 0}
          - {label: "Antigüedad", name: "age", widget: "string"}
          - {label: "Conservación", name: "state", widget: "string"}
          - {label: "Gastos de comunidad", name: "gastos", widget: "string"}
      - label: "Muebles y acabados"
        name: "muebles-acabados"
        widget: "list"
        required: false
        fields:
          - {label: "Item", name: "item", widget: "string"}
      - label: "Equipamiento e instalaciones"
        name: "equipamiento"
        widget: "list"
        required: false
        fields:
          - {label: "Item", name: "item", widget: "string"}
      - label: "Exteriores"
        name: "exteriores"
        widget: "list"
        required: false
        fields:
          - {label: "Item", name: "item", widget: "string"}
      - label: "Certificado energético"
        name: "certificado-energetico"
        widget: "list"
        required: false
        fields:
          - {label: "Item", name: "item", widget: "string"}

  - name: "data"
    label: "Data"
    files:
      - name: "operaciones"
        label: "Operaciones"
        file: "_data/operaciones.yml"
        widget: "list"
        field:
          - {name: "operacion", widget: "string"}
